# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

row_kron <- function(X, Y) {
    .Call(`_CRFpackageRobust_row_kron`, X, Y)
}

IndGreater <- function(x) {
    .Call(`_CRFpackageRobust_IndGreater`, x)
}

IndLess <- function(x) {
    .Call(`_CRFpackageRobust_IndLess`, x)
}

IndEqual <- function(x) {
    .Call(`_CRFpackageRobust_IndEqual`, x)
}

Ind2 <- function(x, y, a, b) {
    .Call(`_CRFpackageRobust_Ind2`, x, y, a, b)
}

risksetC <- function(x, y) {
    .Call(`_CRFpackageRobust_risksetC`, x, y)
}

DeltaC <- function(x, y) {
    .Call(`_CRFpackageRobust_DeltaC`, x, y)
}

logLikC <- function(riskset1, riskset2, logtheta1, logtheta2, delta1, delta2, I1, I2, I3, I4, I5, I6, idxN1, idxN2) {
    .Call(`_CRFpackageRobust_logLikC`, riskset1, riskset2, logtheta1, logtheta2, delta1, delta2, I1, I2, I3, I4, I5, I6, idxN1, idxN2)
}

gradientNew <- function(riskset1, riskset2, logtheta1, logtheta2, delta1, delta2, I1, I2, I3, I4, I5, I6, X1, X2, idxN1, idxN2) {
    .Call(`_CRFpackageRobust_gradientNew`, riskset1, riskset2, logtheta1, logtheta2, delta1, delta2, I1, I2, I3, I4, I5, I6, X1, X2, idxN1, idxN2)
}

meat <- function(riskset1, riskset2, logtheta1, logtheta2, delta1, delta2, I1, I2, I3, I4, I5, I6, X1, X2, idxN1, idxN2, penalty) {
    .Call(`_CRFpackageRobust_meat`, riskset1, riskset2, logtheta1, logtheta2, delta1, delta2, I1, I2, I3, I4, I5, I6, X1, X2, idxN1, idxN2, penalty)
}

gradientPoly <- function(riskset1, riskset2, logtheta1, logtheta2, deriv, df, delta1, delta2, I1, I2, I3, I4, I5, I6) {
    .Call(`_CRFpackageRobust_gradientPoly`, riskset1, riskset2, logtheta1, logtheta2, deriv, df, delta1, delta2, I1, I2, I3, I4, I5, I6)
}

hessianNew <- function(riskset1, riskset2, logtheta1, logtheta2, delta1, delta2, I1, I2, I3, I4, X1, X2, idxN1, idxN2) {
    .Call(`_CRFpackageRobust_hessianNew`, riskset1, riskset2, logtheta1, logtheta2, delta1, delta2, I1, I2, I3, I4, X1, X2, idxN1, idxN2)
}

hessianPolyC <- function(riskset1, riskset2, logtheta1, logtheta2, deriv, df, delta1, delta2, I1, I2, I3, I4) {
    .Call(`_CRFpackageRobust_hessianPolyC`, riskset1, riskset2, logtheta1, logtheta2, deriv, df, delta1, delta2, I1, I2, I3, I4)
}

